### ISSUE TITLE
Doesn't work with hours?

### ISSUE THREAD

**Issue by maxfriedmann** [mikaelhm/angular-countdown-timer#1]
I just had a brief look, wanted to use it for a 24h countdown. But if I set the time to e.g. 2h = 7200s and adopt the output-format I get 3h to count down.

http://jsfiddle.net/ndgf5etf/

**Comment by mikaelhm** [comment]
It doesn't work with hours.

I believe it's because it uses moment.js
Which is actually a DateTime so hour might be an offset depending on
TimeZone or something like that.
